<?php

$items = [
    [
        'id' => 1,
        'tipo' => "weapons",
        'categoria' => "axes",
        'nome' => "Memorial Axes",
        'img' => "https://user.wartale.com/images/items/itWA310.jpg",
        'handed' => 2,
        'spec' => [],
        'mix' => [],
        'age' => [],
        'requirements' => [
            'level' => 146,
            'forca' => 360,
            'talento' => 95,
        ],
        'base_status' => [
            'min_demage' => ["min" => 146, "max" => 152],
            'max_demage' => [164, 167],
            'attack_speed' => 8,
            'critical_base' => 22,
            'attack_rating_base' => [372, 385],
            'block_base' => [12, 13],
            'integrity_base' => [320, 340],
        ],
        'spec_status' => [
            'critical_spec' => 4,
            'attack_power_spec' => "Lv/7",
            'attack_rating_spec' => "Lv/1 - 3",
        ],
        'misc' => [
            'primary_spec' => ["FS"],
            'secondary_spec' => ["MS", "PS"],
            'weight' => 142,
            'price' => 3920000,
        ],
    ],
    [
        'id' => 2,
        'tipo' => "weapons",
        'categoria' => "axes",
        'nome' => "Havoc Axe",
        'img' => "https://user.wartale.com/images/items/itWA309.jpg",
        'handed' => 1,
        'spec' => [],
        'mix' => [],
        'age' => [],
        'requirements' => [
            'level' => 142,
            'forca' => 340,
            'talento' => 90,
        ],
        'base_status' => [
            'min_demage' => [115, 123],
            'max_demage' => [135, 140],
            'attack_speed' => 8,
            'critical_base' => 15,
            'attack_rating_base' => [327, 349],
            'block_base' => [0],
            'integrity_base' => [310, 330],
        ],
        'spec_status' => [
            'critical_spec' => 4,
            'attack_power_spec' => "Lv/7",
            'attack_rating_spec' => "Lv/1 - 3",
        ],
        'misc' => [
            'primary_spec' => ["FS"],
            'secondary_spec' => ["MS", "PS"],
            'weight' => 136,
            'price' => 3410000,
        ],
    ],
    [
        'id' => 3,
        'tipo' => "weapons",
        'categoria' => "axes",
        'nome' => "Zealous Axe",
        'img' => "https://user.wartale.com/images/items/itWA308.jpg",
        'handed' => 2,
        'spec' => [],
        'mix' => [],
        'age' => [],
        'requirements' => [
            'level' => 138,
            'forca' => 320,
            'talento' => 90,
        ],
        'base_status' => [
            'min_demage' => [132, 138],
            'max_demage' => [147, 150],
            'attack_speed' => 8,
            'critical_base' => 22,
            'attack_rating_base' => [314, 327],
            'block_base' => [12],
            'integrity_base' => [295, 315],
        ],
        'spec_status' => [
            'critical_spec' => 4,
            'attack_power_spec' => "Lv/7",
            'attack_rating_spec' => "Lv/1 - 3",
        ],
        'misc' => [
            'primary_spec' => ["FS"],
            'secondary_spec' => ["MS", "PS"],
            'weight' => 130,
            'price' => 3030000,
        ],
    ],
    [
        'id' => 4,
        'tipo' => "weapons",
        'categoria' => "axes",
        'nome' => "Deadly Axe",
        'img' => "https://user.wartale.com/images/items/itWA128.jpg",
        'handed' => 2,
        'spec' => [],
        'mix' => [],
        'age' => [],
        'requirements' => [
            'level' => 134,
            'forca' => 300,
            'talento' => 90,
        ],
        'base_status' => [
            'min_demage' => [125, 131],
            'max_demage' => [139, 142],
            'attack_speed' => 8,
            'critical_base' => 22,
            'attack_rating_base' => [286, 298],
            'block_base' => [12],
            'integrity_base' => [280, 300],
        ],
        'spec_status' => [
            'critical_spec' => 4,
            'attack_power_spec' => "Lv/7",
            'attack_rating_spec' => "Lv/1 - 3",
        ],
        'misc' => [
            'primary_spec' => ["FS"],
            'secondary_spec' => ["MS"],
            'weight' => 122,
            'price' => 2650000,
        ],
    ],
    [
        'id' => 5,
        'tipo' => "weapons",
        'categoria' => "axes",
        'nome' => "Mythology Axe",
        'img' => "https://user.wartale.com/images/items/itWA307.jpg",
        'handed' => 2,
        'spec' => [],
        'mix' => [],
        'age' => [],
        'requirements' => [
            'level' => 130,
            'forca' => 280,
            'talento' => 90,
        ],
        'base_status' => [
            'min_demage' => [118, 124],
            'max_demage' => [132, 135],
            'attack_speed' => 8,
            'critical_base' => 21,
            'attack_rating_base' => [271, 283],
            'block_base' => [12],
            'integrity_base' => [260, 280],
        ],
        'spec_status' => [
            'critical_spec' => 4,
            'attack_power_spec' => "Lv/7",
            'attack_rating_spec' => "Lv/1 - 3",
        ],
        'misc' => [
            'primary_spec' => ["FS"],
            'secondary_spec' => ["MS"],
            'weight' => 112,
            'price' => 2250000,
        ],
    ],
    [
        'id' => 6,
        'tipo' => "weapons",
        'categoria' => "axes",
        'nome' => "Kronos Axe",
        'img' => "https://user.wartale.com/images/items/itWA124.jpg",
        'handed' => 2,
        'spec' => [],
        'mix' => [],
        'age' => [],
        'requirements' => [
            'level' => 126,
            'forca' => 260,
            'talento' => 90,
        ],
        'base_status' => [
            'min_demage' => [111, 117],
            'max_demage' => [125, 128],
            'attack_speed' => 8,
            'critical_base' => 21,
            'attack_rating_base' => [258, 270],
            'block_base' => [12],
            'integrity_base' => [240, 260],
        ],
        'spec_status' => [
            'critical_spec' => 4,
            'attack_power_spec' => "Lv/7",
            'attack_rating_spec' => "Lv/1 - 3",
        ],
        'misc' => [
            'primary_spec' => ["FS"],
            'secondary_spec' => ["MS"],
            'weight' => 103,
            'price' => 2200000,
        ],
    ],
    [
        'id' => 7,
        'tipo' => "weapons",
        'categoria' => "axes",
        'nome' => "Gladiator Axe",
        'img' => "https://user.wartale.com/images/items/itWA306.jpg",
        'handed' => 1,
        'spec' => [],
        'mix' => [],
        'age' => [],
        'requirements' => [
            'level' => 122,
            'forca' => 245,
            'talento' => 90,
        ],
        'base_status' => [
            'min_demage' => [89, 92],
            'max_demage' => [112, 115],
            'attack_speed' => 8,
            'critical_base' => 14,
            'attack_rating_base' => [228, 241],
            'block_base' => [0],
            'integrity_base' => [230, 250],
        ],
        'spec_status' => [
            'critical_spec' => 4,
            'attack_power_spec' => "Lv/7",
            'attack_rating_spec' => "Lv/1 - 3",
        ],
        'misc' => [
            'primary_spec' => ["FS"],
            'secondary_spec' => ["MS"],
            'weight' => 92,
            'price' => 2150000,
        ],
    ],
    [
        'id' => 8,
        'tipo' => "weapons",
        'categoria' => "axes",
        'nome' => "Dragon Axe",
        'img' => "https://user.wartale.com/images/items/itWA123.jpg",
        'handed' => 2,
        'spec' => [],
        'mix' => [],
        'age' => [],
        'requirements' => [
            'level' => 120,
            'forca' => 230,
            'talento' => 90,
        ],
        'base_status' => [
            'min_demage' => [104, 109],
            'max_demage' => [118, 121],
            'attack_speed' => 8,
            'critical_base' => 21,
            'attack_rating_base' => [245, 257],
            'block_base' => [12],
            'integrity_base' => [220, 240],
        ],
        'spec_status' => [
            'critical_spec' => 4,
            'attack_power_spec' => "Lv/7",
            'attack_rating_spec' => "Lv/1 - 3",
        ],
        'misc' => [
            'primary_spec' => ["FS"],
            'secondary_spec' => ["MS"],
            'weight' => 98,
            'price' => 2100000,
        ],
    ],
    [
        'id' => 9,
        'tipo' => "weapons",
        'categoria' => "axes",
        'nome' => "Demolition Axe",
        'img' => "https://user.wartale.com/images/items/itWA305.jpg",
        'handed' => 2,
        'spec' => [],
        'mix' => [],
        'age' => [],
        'requirements' => [
            'level' => 116,
            'forca' => 220,
            'talento' => 90,
        ],
        'base_status' => [
            'min_demage' => [100, 105],
            'max_demage' => [113, 116],
            'attack_speed' => 8,
            'critical_base' => 20,
            'attack_rating_base' => [236, 249],
            'block_base' => [12],
            'integrity_base' => [215, 235],
        ],
        'spec_status' => [
            'critical_spec' => 4,
            'attack_power_spec' => "Lv/7",
            'attack_rating_spec' => "Lv/1 - 3",
        ],
        'misc' => [
            'primary_spec' => ["FS"],
            'secondary_spec' => ["MS"],
            'weight' => 95,
            'price' => 2050000,
        ],
    ],
];
